# Generated by Django 2.0.6 on 2018-08-05 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('mess_type', models.CharField(max_length=100)),
                ('student_phone_number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits only', regex='^\\d{10}$')])),
                ('parent_phone_number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits only', regex='^\\d{10}$')])),
                ('time_of_leaving', models.TimeField()),
                ('time_of_arrival', models.TimeField()),
                ('viiting_address', models.TextField()),
                ('purpose_of_leaving', models.CharField(max_length=250)),
                ('permanent_address', models.TextField()),
                ('hostel_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ov.HostelBlock')),
            ],
        ),
    ]
