# Generated by Django 2.0.6 on 2018-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0002_outingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='outingform',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
