# Generated by Django 2.0.6 on 2018-08-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0003_outingform_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='outingform',
            name='date_of_outing',
            field=models.DateField(null=True),
        ),
    ]
