# Generated by Django 2.0.6 on 2018-08-07 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0004_outingform_date_of_outing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Registation number should be like 17BCE1007', regex='\\d{2}[a-zA-Z]{3}\\d{4}')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='outingform',
            name='registration_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Registation number should be like 17BCE1007', regex='\\d{2}[a-zA-Z]{3}\\d{4}')]),
        ),
    ]
