# Generated by Django 2.1 on 2018-08-07 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0005_auto_20180807_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Plese give valid registration number', regex='\\d{2}[a-zA-Z]{3}\\d{4}')]),
        ),
    ]
