# Generated by Django 2.0.6 on 2018-08-07 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0006_auto_20180807_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Plese give valid registration number', regex='\\d{2}[a-zA-Z]{3}\\d{4}')]),
        ),
    ]
