# Generated by Django 2.0.6 on 2018-08-07 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0007_auto_20180808_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Plese give valid registration number', regex='\\d{2}[a-zA-Z]{3}\\d{4}')]),
        ),
    ]
